data_facts = {
1: "Eyfel minorasi yozda 15 sm balandroq bo'lishi mumkin.",
    2: "Asal hech qachon buzilmaydi.",
    3: "Aktopuslarning uchta yuragi bor.",
    4: "G'ozlar bir-birlari bilan o'zlarining tilini ishlatib muloqot qilishadi.",
    5: "Ba'zi baliqlar suvsiz yashay olmaydi, lekin ular 5-6 yil davomida havo bilan nafas olishi mumkin.",
    6: "Gepard dunyodagi eng tez yuguruvchi hayvon bo'lib, 110 km/soat tezlikka erishishi mumkin.",
    7: "Ba'zi qushlar yuzi yordamida ko'rishadi.",
    8: "Tushda ko'rgan har bir insonni siz bir marta hayotingizda ko'rgansiz.",
    9: "Ba'zi mollyuskalar o'zlarini bir necha marta yangilashlari mumkin.",
    10: "Tishlar odamning bo'ynida ham o'sadi, lekin ularni ko'rish uchun maxsus uskunalar kerak.",
    11: "Tuyoq bilan yugurish qobiliyatiga ega hayvonlar uzoq masofaga yugurishda qiyinchilikka duch kelishadi.",
    12: "Faqat ayol hayvonlar ona bo'lishi mumkin, erkak hayvonlar esa hech qachon ona bo'lolmaydi.",
    13: "Ayollarning miya ulushi erkaklarnikiga nisbatan kichikroq bo'lishi mumkin.",
    14: "Suvda yashovchi ba'zi hayvonlar o'zlariga elektr toki yordamida ov qilishadi.",
    15: "Ba'zi baliqlar o'zlariga mos maxsus himoya mexanizmlarini ishlab chiqadi.",
    16: "Qushlar balandlikda uchishadi, lekin ba'zilari yuqori tezlikda ham uchishadi.",
    17: "Qushlarning ko'pchiligi o'zlarining kuchli qanotlari bilan yuqori balandliklarga uchishadi.",
    18: "Ba'zi baliqlar suv ostida yashash uchun maxsus mexanizmlarga ega.",
    19: "Tushunish va ko'rish qobiliyatlari o'zgarib turadigan hayvonlar mavjud.",
    20: "Ba'zi baliqlar 10 yildan ko'proq yashashi mumkin.",
    21: "Dunyoda eng katta qush - struҳdir.",
    22: "Ba'zi yirtqich hayvonlar o'z ovlarini to'liq yutishadi.",
    23: "Oqshomda yirik baliqlar suv ostida ko'proq faoliyat ko'rsatadi.",
    24: "Ba'zi baliqlar tishlarini yashirish uchun maxsus mexanizmlarga ega.",
    25: "Ba'zi hayvonlar uzoq vaqt davomida quruqlikda yashay olishadi.",
    26: "Ko'plab baliqlar suvsiz yashay olmaydi.",
    27: "Ba'zi baliqlar yuqori tezlikka erishish uchun yordamchi mexanizmlarga ega.",
    28: "Qushlarning ko'pchiligi o'zlarini o'zgartiradigan mexanizmlarga ega.",
    29: "Baliqlar har xil turdagi suyuqlikni o'zlariga moslashtirishadi.",
    30: "Ba'zi baliqlar uzoq masofalarga suzishadi.",
    31: "Qushlar tez-tez yuqori balandlikdan qulab tushishadi.",
    32: "Ba'zi baliqlar o'zining bo'ynini o'zgartiradi.",
    33: "Ba'zi baliqlar va dengiz hayvonlari o'zlariga o'xshash mexanizmlarga ega.",
    34: "Ba'zi baliqlar suvsiz yashay olishadi.",
    35: "Ba'zi baliqlar o'zlarini himoya qilish uchun elektr toki ishlatishadi.",
    36: "Ba'zi baliqlar suv ostida maxsus hududlarda yashashadi.",
    37: "Ba'zi hayvonlar o'zlarini qandaydir maxsus usulda himoya qilishadi.",
    38: "Hayvonlarning ba'zilari quruqlikda uzoq vaqt yashay olishadi.",
    39: "Ba'zi baliqlar ham bu suvning ichida yashashadi.",
    40: "Yirtqich hayvonlar ba'zan o'z ovlarini birgalikda ov qilishadi.",
    41: "Baliqlar ko'pincha o'zlarini birga ko'rsatadilar.",
    42: "Ba'zi baliqlar yuqori tezlikka erishish uchun o'zlarini maxsus o'zgartirishadi.",
    43: "Ba'zi baliqlar o'zlarini o'zgartirish mexanizmlarini yaratadilar.",
    44: "Ba'zi baliqlar suvsiz yashay olishadi.",
    45: "Ba'zi baliqlar maxsus himoya mexanizmlarini o'zlashtirishadi.",
    46: "Ba'zi baliqlar o'zlarini himoya qilish uchun turli usullarni qo'llashadi.",
    47: "Ba'zi baliqlar uzoq masofani bosib o'tishadi.",
    48: "Ba'zi baliqlar birgalikda o'zlarini boshqarishadi.",
    49: "Ba'zi baliqlar va dengiz hayvonlari yuqori tezlikda suzishadi.",
    50: "Ba'zi hayvonlar bir-birlari bilan o'z maxfiy tillarida muloqot qilishadi."
}

data_tasks = {
    1: "15 daqiqa o'qing",
    2: "10 marta push-up qiling",
    3: "Jurnalga yozuv yozing",
    4: "Bir daqiqa davomida chuqur nafas oling",
    5: "5 daqiqa davomida meditatsiya qiling",
    6: "Biror yangi narsani o'rganing",
    7: "Biror yangi so'z o'rgating",
    8: "10 daqiqa davomida yuring",
    9: "Kitobdan bir bo'lim o'qing",
    10: "5 daqiqa davomida qisqa mashqlar qiling",
    11: "Yangi bir tabiat hodisasini o'rganing",
    12: "5 daqiqa davomida teginish terapiyasi bilan shug'ullaning",
    13: "Telefoningizni 30 daqiqaga qo'yib, dam oling",
    14: "Biror yangi odam bilan suhbatlashing",
    15: "30 daqiqa davomida sevimli musiqangizni tinglang",
    16: "Biror qisqa video darsni tomosha qiling",
    17: "Shaxsiy maqsadlar ro'yxatini tuzing",
    18: "Biror narsaga minnatdorchilik bildiring",
    19: "Biror narsani yangi yo'l bilan bajaring",
    20: "30 daqiqa davomida kompyuterda ishlashdan tanaffus qiling",
    21: "5 daqiqa davomida stressni kamaytirish mashqlarini bajaring",
    22: "Sog'lom nonushta tayyorlang",
    23: "10 marta dastlabki yordam usullarini ko'rib chiqing",
    24: "Biror foydali video yoki maqola o'qing",
    25: "Yangi bir ovqat retseptini o'rganing",
    26: "Biror tasvirni chizing",
    27: "Biror foydali odatni sinab ko'ring",
    28: "10 daqiqa davomida yoga qiling",
    29: "O'zgarishlar uchun xat yozing",
    30: "Har kuni o'qishga vaqt ajrating",
    31: "15 daqiqa davomida yozishni mashq qiling",
    32: "O'z maqsadingizni yozib chiqing",
    33: "Kundalik ishlarga reja tuzing",
    34: "10 daqiqa davomida sport bilan shug'ullaning",
    35: "Deyarli o'zingizni tasvirlab yozing",
    36: "Biror eski do'stingiz bilan bog'laning",
    37: "Biror g'oyani qog'ozga tushiring",
    38: "Biror yangi kitob boshlang",
    39: "10 daqiqa davomida tabiatda sayr qiling",
    40: "Tush kuningizni rejalashtiring",
    41: "O'z vaqtida turish va uxlash uchun rejalar tuzing",
    42: "30 daqiqa davomida sevgan ishingiz bilan shug'ullaning",
    43: "O'z salomatligingizni yaxshilash uchun mashq qiling",
    44: "Sevimli mashg'ulotingizni boshlang",
    45: "Yangi bir hobbi sinab ko'ring",
    46: "Biror ijtimoiy tarmoqdagi do'stlaringiz bilan bog'laning",
    47: "Biror yangi joyni ziyorat qiling",
    48: "Boshqa madaniyatni o'rganing",
    49: "5 daqiqa davomida kundalik rejangizni ko'rib chiqing",
    50: "Birinchi bo'lib yong'oq yeyishni sinab ko'ring"
}